### ISSUE TITLE
Error submitting data

### ISSUE THREAD

**Issue by Zoidzoid** [AnotherStranger/rockbox-scrobbler#42]
I have used this tool in windows 10 and came across this error while submitting data to ListenBrainz:

```
C:\Users\...\AppData\Local\Temp\ONEFIL~1\rockbox_listenbrainz_ui.py:128: DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead.
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\pylistenbrainz\client.py", line 137, in _post
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\requests\models.py", line 1024, in raise_for_status requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://api.listenbrainz.org/1/submit-listens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\rockbox_listenbrainz_ui.py", line 158, in submit_data
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\rockbox_listenbrainz_scrobbler\scrobbling.py", line 50, in scrobble_multiple
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\pylistenbrainz\client.py", line 198, in submit_multiple_listens
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\pylistenbrainz\client.py", line 161, in _post_submit_listens
  File "C:\Users\...\AppData\Local\Temp\ONEFIL~1\pylistenbrainz\client.py", line 146, in _post pylistenbrainz.errors.ListenBrainzAPIException
```

**Comment by AnotherStranger** [comment]
Hey @Zoidzoid,
I never used this tool on Windows myself. I will have a look this evening.
Thank you for reaching out!

**Comment by AnotherStranger** [comment]
@Zoidzoid Apparently the Library I used to interface with ListenBrainz created an invalid JSON.
Do you have the rockbox log file at hand? If so, can you either check the timestamps of paste part of the file here? This would help me to identify the issue.

**Comment by Zoidzoid** [comment]
Reverend Horton Heat	Rev	Hardscrabble Woman	12	219	L	1721063664	
Garbage	Beautifulgarbage	Parade	10	249	L	1721063851	
Rancid	...And Out Come The Wolves	Avenues & Alleyways	18	192	L	1721064506	
Skank	Calango	Chega Disso!	8	245	L	1721064698	
Big D and the Kids Table	Shot by Lammi	What?	5	73	L	1721064942	
Art Brut	Bang Bang Rock & Roll	Moving To L.A.	9	209	L	1721065015	
Rancid	Rancid	Black Derby Jacket	16	155	L	1721065321	
The Mighty Mighty Bosstones	A Jackknife To A Swan	You Can't Win	8	199	L	1721065477	
Less Than Jake	Anthem	The Upwards War And The Down Turned Cycle	7	180	L	1721065676	
Joy Division	Permanent	Atmosphere	15	250	L	1721065856	
Skankin' Pickle	Green Album	Rest Of The World	5	91	L	1721066106
[.scrobble.log](https://github.com/user-attachments/files/17883126/default.scrobble.log)

**Comment by AnotherStranger** [comment]
@Zoidzoid Thank you for providing your Logfile! With this I think I could solve the Issue. Can you test again with the new Release?

**Comment by Zoidzoid** [comment]
Thanks for the work. Unfortunately my Antivirus did not let me run the app. It was flagged as a Trojan.

**Comment by AnotherStranger** [comment]
Hey @Zoidzoid,
unfortunately it seems like many Antivirus flag Applications built with nuitka as malware.

> [Windows Virus Scanners](https://nuitka.net/user-documentation/common-issue-solutions.html#windows-virus-scanners)
>
> Some Antivirus Vendors may flag compile binaries using Nuitka’s default settings on Windows as malware. That happens  a lot if you compile without additional steps. You can avoid this by purchasing the [Nuitka Commercial](https://nuitka.net/doc/commercial.html) plan and following the instructions given. You can solve it with those instructions and support, but there are no guarantees.

However, I switched from compiling everything into one file to creating a standalone app. Feel free to give it a try. (See the new release)

**Comment by Zoidzoid** [comment]
Thank you so much!

It did work flawlessly this time.

**Comment by Zoidzoid** [comment]
Thank you so much!

It did work flawlessly this time.

**Comment by AnotherStranger** [comment]
@Zoidzoid I'm glad that I cloud help. Tbh I never thought that anyone was using this App 👀

**Comment by Zoidzoid** [comment]
Well, I gave you credit in the ListenBrainz forum. Maybe there are more people in my position.
